version: '3.8'

services:
  app1:
    image: volumetest0:dev
    build:
      context: .
      dockerfile: VolumeTest/Dockerfile
    ports:
      - "5001:8080"   
    volumes:
      - error_volume:/app
      - info_volume:/app 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  app2:
    image: volumetest0:dev
    build:
      context: .
      dockerfile: VolumeTest/Dockerfile
    ports:
      - "5002:8080"  
    volumes:
      - error_volume:/app
      - info_volume:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  error_volume:
    external: true
  info_volume:
    external: true
